### ISSUE TITLE
Why does acugen make run multiple variant calling tools? 

### ISSUE THREAD

**Issue by calledit** [AcuRARE/acugen#1]
A question.

Why does acugen make run multiple variant calling tools, then merge the result?

What is the purpose of that?

**Comment by Thage** [comment]
Hello,

This pipeline was primarily used in rare disease research, where it was important that we identify all potential variants. The merged VCF file compiled every variant detected by the different callers, resulting in a high number of false positives but a low number of false negatives.

**Comment by calledit** [comment]
The filtering seams sort of strange then.
https://github.com/AcuRARE/acugen/blob/6700c62788da2397d86dcdfc5087a81daff90270/acugen_main.py#L255

Especially when using freebayes and not filtering for QUAL, most of the calls coming from freebayes are of very low quality they write in their readme that you are expected to run it like this:
`freebayes -f ref.fa aln.bam | vcffilter -f "QUAL > 20" >vars.vcf` 
Otherwise you get a file with calls that are like QUAL = 3.13896e-10 or so.

Anyway, thanks for answering!
